"""create clinician model

Revision ID: 97e06562d84d
Revises: 78ff68132d18
Create Date: 2026-03-02 13:09:01.670589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e06562d84d'
down_revision: Union[str, Sequence[str], None] = '78ff68132d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('credentials', sa.String(length=255), nullable=False),
    sa.Column('registration_id', sa.String(length=100), nullable=False),
    sa.Column('certificates', sa.Text(), nullable=True),
    sa.Column('consultation_fee', sa.Integer(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='clinician_status_enum'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinicians_registration_id'), 'clinicians', ['registration_id'], unique=True)
    op.create_index(op.f('ix_clinicians_user_id'), 'clinicians', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinicians_user_id'), table_name='clinicians')
    op.drop_index(op.f('ix_clinicians_registration_id'), table_name='clinicians')
    op.drop_table('clinicians')
    # ### end Alembic commands ###
